version: "3"

services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#environment
    env_file: ./sonarqube_pass.env
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    # networks:
    #   - frontend
    #   - backend
  db:
    image: postgres:12
    env_file: ./postgres_pass.env
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    # networks:
    #   - default
    #   - backend
  # proxy:
  #   image: nginx
  #   volumes:
  #     - templates:/etc/nginx/templates
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - NGINX_HOST=proxy.company.com
  #     - NGINX_PORT=80
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  # templates:

# networks:
#   default:
#     external: true # If you want your containers to join a pre-existing network, use the external option:
#     driver: none # remove sonarqube connetion to the internet
#   frontend:
#     driver: bridge
#   backend:
#     driver: bridge