---
#https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html && https://serverfault.com/questions/540492/sudo-echo-bla-etc-sysctl-conf-permission-denied
## https://hub.docker.com/_/sonarqube
- name: Increase vm.max_map_count=262144 or Sonarqube will container will exit [ sudo sed -i '/^vm.max_map_count.*$/d' /etc/sysctl.conf && sudo sed -i "$ a vm.max_map_count=262144" /etc/sysctl.conf && sysctl -w vm.max_map_count=262144 ]
  command: "{{item}}"
  become: true
  become_user: "{{root_user}}"
  loop:
    - "sed -i '/^vm.max_map_count.*$/d' /etc/sysctl.conf"
    - "sed -i '$ a vm.max_map_count=262144' /etc/sysctl.conf"
    - "sysctl -w vm.max_map_count=262144"
    - "sed -i '/^fs.file-max.*$/d' /etc/sysctl.conf" 
    - "sed -i '$ a fs.file-max=131072' /etc/sysctl.conf"
    - "sysctl -w fs.file-max=131072"
    - "bash -c 'ulimit -n 131072'"
    - "bash -c 'ulimit -u 8192'"

# # TODO: generate the ./sonarqube/*_pass.env files from a templated file and then remove the password files
# - name: Start the sonarqube containers, detach previously started containers [ cd ./sonarqube && docker-compose up -d && cd .. ]
#   command: "echo injected passwords"

# NOTE: need to CD into folder because using [ docker-compose -f ./sonarqube/docker-compose.yml ] does not work
# NOTE: CD is a BASH builtin and not an actual executable [ https://stackoverflow.com/questions/3741148/location-of-cd-executable ]
# TODO: -d aka detach can be an issue for elastic search and sonarqube processing ongoing requests, will need to see another way to restart safely the containers
- name: Start the sonarqube containers, detach previously started containers [ cd ./sonarqube && docker-compose up -d && cd .. ]
  # command: "bash -c 'cd ./sonarqube && docker-compose up -d --force-recreate'"
  command: "{{item}}"
  become: true
  become_user: "{{ansible_user}}"
  loop: 
    - "bash -c 'sudo chmod +x ./sonarqube/start-docker.sh'"
    - "bash ./sonarqube/start-docker.sh"